const issuers_list = [
	{ name: "Barclays Bank", issuer_code: "BRSP", id: 1 },
	{ name: "BBVA Global Markets", issuer_code: "BBVL", id: 2 },
	{ name: "Banque Cantonale Vaudoise", issuer_code: "BCVS", id: 3 },
	{ name: "BNP Paribas Issuance", issuer_code: "BNPA", id: 4 },
	{ name: "Canadian Imperial", issuer_code: "", id: 5 },
	{ name: "Citigroup Luxembourg", issuer_code: "CGSP", id: 6 },
	{ name: "Commerzbank", issuer_code: "CBED", id: 7 },
	{ name: "Credit Suisse", issuer_code: "CSSS", id: 8 },
	{ name: "EFG International Finance", issuer_code: "LEOZ", id: 9 },
	{ name: "Exane Finance", issuer_code: "EXAD", id: 10 },
	{ name: "Goldman Sachs International", issuer_code: "GSSD", id: 11 },
	{ name: "Goldman Sachs Finance Corp", issuer_code: "GSSD", id: 12 },
	{ name: "HSBC Bank", issuer_code: "HSED", id: 13 },
	{ name: "Investec Bank", issuer_code: "IVSS", id: 14 },
	{ name: "J.P Morgan", issuer_code: "JPM", id: 15 },
	{ name: "Bank Julius Baer", issuer_code: "JBST", id: 16 },
	{ name: "Leonteq Securities", issuer_code: "LEOZ", id: 17 },
	{ name: "Luzerner Kantonalbank", issuer_code: "LUKB", id: 18 },
	{ name: "Marex Financial", issuer_code: "MARE", id: 19 },
	{ name: "Morgan Stanley B.V.", issuer_code: "MSIP", id: 20 },
	{ name: "Natixis Structured Issuance", issuer_code: "NXED", id: 21 },
	{ name: "Nomura International Funding", issuer_code: "NOMX", id: 22 },
	{ name: "Raiffeisen Switzerland", issuer_code: "LEOZ", id: 23 },
	{ name: "Royal Bank of Canada", issuer_code: "RBCD", id: 24 },
	{ name: "SG Issuer", issuer_code: "SGDP", id: 25 },
	{ name: "UBS AG (London)", issuer_code: "UBSF", id: 26 },
	{ name: "Bank Vontobel", issuer_code: "VONT", id: 27 },
	{ name: "Zürcher Kantonalbank", issuer_code: "ZKBZ", id: 28 },
	{ name: "UBS AG (Guernsey)", issuer_code: "UBSF", id: 29 },
	{ name: "Bank J. Safra Sarasin", issuer_code: "SARA", id: 30 },
	{ name: "Crédit Agricole", issuer_code: "CL", id: 31 },
	{ name: "Banque Internationale à Luxembourg", issuer_code: "LEOZ", id: 32 },
	{ name: "Morgan Stanley & Co International", issuer_code: "MSIP", id: 33 },
	{ name: "Cornèr Bank", issuer_code: "LEOZ", id: 34 },
	{ name: "Itau BBA International", issuer_code: "BIEU", id: 35 },
];

module.exports = issuers_list;
